#   Copyright (c) European Space Agency, 2025.
#
#   This file is subject to the terms and conditions defined in file 'LICENCE.txt', which
#   is part of this source code package. No part of the package, including
#   this file, may be copied, modified, propagated, or distributed except according to
#   the terms contained in the file ‘LICENCE.txt’.

name: gaia_exorbitml
channels:
  - conda-forge
  - microsoft
dependencies:
  - _py-xgboost-mutex=2.0
  - asttokens=2.4.1
  - aws-c-auth=0.7.7
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.8
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.14
  - aws-c-io=0.13.35
  - aws-c-mqtt=0.9.9
  - aws-c-s3=0.3.24
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.24.7
  - aws-sdk-cpp=1.11.182
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bokeh=3.3.3
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.21.0
  - ca-certificates=2023.11.17
  - cairo=1.18.0
  - certifi=2023.11.17
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.2.0
  - cramjam=2.7.0
  - cycler=0.12.1
  - cytoolz=0.12.2
  - dask=2023.12.1
  - dask-core=2023.12.1
  - dbus=1.13.6
  - debugpy=1.8.0
  - decorator=5.1.1
  - distributed=2023.12.1
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - expat=2.5.0
  - fastparquet=2023.10.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.44.3
  - freetype=2.12.1
  - fsspec=2023.10.0
  - gettext=0.21.1
  - gflags=2.2.2
  - glib=2.78.1
  - glib-tools=2.78.1
  - glog=0.6.0
  - graphite2=1.3.13
  - gst-plugins-base=1.22.7
  - gstreamer=1.22.7
  - harfbuzz=8.3.0
  - icu=73.2
  - imbalanced-learn=0.11.0
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - iniconfig=2.0.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230802.1
  - libarrow=14.0.1
  - libarrow-acero=14.0.1
  - libarrow-dataset=14.0.1
  - libarrow-flight=14.0.1
  - libarrow-flight-sql=14.0.1
  - libarrow-gandiva=14.0.1
  - libarrow-substrait=14.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcurl=8.4.0
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcrypt=1.10.2
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libgoogle-cloud=2.12.0
  - libgpg-error=1.47
  - libgrpc=1.59.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libogg=1.3.4
  - libopenblas=0.3.24
  - libopus=1.3.1
  - libparquet=14.0.1
  - libpng=1.6.39
  - libpq=16.1
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.44.0
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxgboost=1.7.6
  - libxml2=2.11.6
  - libzlib=1.2.13
  - llvmlite=0.41.1
  - locket=1.0.0
  - loguru=0.7.2
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.1
  - matplotlib-base=3.8.1
  - matplotlib-inline=0.1.6
  - mpg123=1.32.3
  - msgpack-python=1.0.7
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nspr=4.35
  - nss=3.94
  - numba=0.58.1
  - numpy=1.26.0
  - openjpeg=2.5.0
  - openssl=3.2.0
  - orc=1.9.0
  - packaging=23.2
  - pandas=2.1.3
  - parso=0.8.3
  - partd=1.4.1
  - patsy=0.5.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pip=23.3.1
  - pixman=0.42.2
  - platformdirs=4.0.0
  - pluggy=1.3.0
  - ply=3.11
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=1.7.6
  - pyarrow=14.0.1
  - pyarrow-hotfix=0.6
  - pygments=2.17.0
  - pyod=1.1.2
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - pytest=7.4.3
  - python=3.11.6
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qt-main=5.15.8
  - re2=2023.06.02
  - readline=8.2
  - s2n=1.3.56
  - scikit-learn=1.3.2
  - scipy=1.11.3
  - seaborn=0.13.0
  - seaborn-base=0.13.0
  - setuptools=68.2.2
  - shap=0.44.0
  - sip=6.7.12
  - six=1.16.0
  - slicer=0.0.7
  - snappy=1.1.10
  - sortedcontainers=2.4.0
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - tblib=3.0.0
  - threadpoolctl=3.2.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.13.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - urllib3=2.1.0
  - wcwidth=0.2.10
  - wheel=0.41.3
  - xgboost=1.7.6
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5